### ISSUE TITLE
support mat-table with native table

### ISSUE THREAD

**Issue by amirlpro** [SortableJS/ngx-sortablejs#130]
the internal structure of mat-table creates children inside &lt;tbody&gt; however this element is not accessible thus I can't apply [sortablejs] to this element.
please add a way to provide a css selector for sortablejs options, this way it will dynamically get the list container. for instance {container: 'tbody'} will select the first tbody child inside mat-table if the directive applied on mat-table.

**Comment by dalexander-trc** [comment]
Wondering if this is possible yet? I've tried a few things without success so far.

**Comment by smnbbrv** [comment]
Please check 3.1.0 and its `sortablejsContainer`. Specify the selector, e.g. `sortablejsContainer="tbody"` and that should do the job.
