### ISSUE TITLE
When using an Array of objects, swapping of rows is not detected by the form 

### ISSUE THREAD

**Issue by yonas-adane** [SortableJS/ngx-sortablejs#138]
I'm trying to build sortable rows using the "angular-sortablejs" library. The sorting part on the UI works fine. But, when swapping rows, the object array (myForm.value) doesn't detect/show the change/s. i.e., the order of objects in the array or form stays the same.

Here is a link to demo my question. 
https://stackblitz.com/edit/angular-ydw4ri

As you can see, myForm.value shows changes when typing into the text inputs (New Order and Name columns).  But when you drag and drop to swap rows, myForm.value does not show the changes due to the swap/drag & drop.

Thanks!

**Comment by smnbbrv** [comment]
hi

you are passing an array instance as a binding, but checking the FormArray value after sorting. You need to choose one or another. Either pass the FormArray instance to the sortablejs or use cities to print the value from
