### ISSUE TITLE
Is it possible drop a parent item into another parent as a child?

### ISSUE THREAD

**Issue by TrickTrackers** [SortableJS/ngx-sortablejs#140]
I have nested list and i can drop child of one parent into another parent. But i cant drop parent into another parent as a child. Is there any possibility?

**Comment by smnbbrv** [comment]
You are describing the tree, aren't you?

https://stackblitz.com/edit/angular-o1pq84 or https://stackblitz.com/edit/angular-ptu94s (they are also mentioned in the README)

**Comment by TrickTrackers** [comment]
Thanks bro.
