### ISSUE TITLE
update position for the dragged item

### ISSUE THREAD

**Issue by Mrdogithub** [SortableJS/ngx-sortablejs#141]
Hi

could you let me know how to update the position when i dropped the dragged item into another area , so that the item will be placed the position where i dropped.

Thanks.

**Comment by smnbbrv** [comment]
Hi,

please have a look here https://smnbbrv.github.io/angular-sortablejs-demo/multiple-lists . 

Does it help to answer your question?

**Comment by Mrdogithub** [comment]
@smnbbrv  thanks for your reply
i mean that when i drop the item i can update the position left and top ,so that it can be placed any place when mouse up

**Comment by Amanda1995pig** [comment]
I have the same question,I try to update the options in the onChoose event.And,I check it at the console ,the options have been changed when mouse down，but it does't work before mouse up. only do I click the item at the second time,it can be worked.Maybe you can try this method to update options, but I can't  promise it will success.
