### ISSUE TITLE
New null element on some situations.

### ISSUE THREAD

**Issue by lucciano** [SortableJS/ngx-sortablejs#142]
On a sortable of object / components sometimes it add a empty (null) element to the list.
I think it may be related to  #76 .

**Comment by lucciano** [comment]
I try to reproduce, but i can't. I make the stackblitz for that porpuse, and realize that i do have an extra empty element following the *ngFor element, with may acount for this behavior. In other application I thought that this was the behavior and we mitigated by reloading the app after the sort.

https://stackblitz.com/edit/angular-mvlfs2

**Comment by smnbbrv** [comment]
Hi @lucciano

Does that mean that there is no issue? 😀

Of course if you have other elements inside the same parent they will participate sorting unless you block them with draggable selector or filter options

**Comment by smnbbrv** [comment]
no issue => closing
