### ISSUE TITLE
Drag modal inside ngFor

### ISSUE THREAD

**Issue by diegoferreirax** [SortableJS/ngx-sortablejs#144]
HI @smnbbrv 

I have a problem with the usability of a modal for each "item" in ngFor. When I hold the mouse button on the modal, it does the modal drag and it generates a bug. The modal goes to the location of the item and only the opacity of the modal is on screen and I can not do anything else. Just restart the page to continue using the application. Thank you!

**Comment by smnbbrv** [comment]
hi,

which sortablejs version do you have installed? Recently there was a 1.8.1 released which broke some stuff.

Is it reproducible on 1.7.0?

**Comment by smnbbrv** [comment]
Info missing / reproduction needed
