### ISSUE TITLE
How can drag and drop items between two components

### ISSUE THREAD

**Issue by fujale** [SortableJS/ngx-sortablejs#146]
Could you please let me know how can we drag and drop items from left component to right component.

Inside an app.component.html we have below:
app-left
app-right

Need to drag the items from <app-left> to <app-right>. Please, any help would save my life.

**Comment by smnbbrv** [comment]
Hi

here you can find an example https://smnbbrv.github.io/angular-sortablejs-demo/multiple-lists and its source code https://github.com/smnbbrv/angular-sortablejs-demo/tree/master/src/app/examples/multiple-lists

is this helpful?

**Comment by fujale** [comment]
Hi @smnbbrv,

Thanks for your response.

The examples shown in the URL's are within the component. In my case need to drag the element from one component and drop in another component.

Please, any help would be apricated.

**Comment by fujale** [comment]
Can any help me out?

**Comment by smnbbrv** [comment]
hi

what is the difference? I mean, two components, one component, just use the same group name.

also see https://github.com/smnbbrv/angular-sortablejs-demo/tree/master/src/app/test-cases/cross-components-multiple-lists
