### ISSUE TITLE
Upgrade angular-sortablejs to Sortablejs 1.8.1 (Latest)

### ISSUE THREAD

**Issue by bhaskerchari** [SortableJS/ngx-sortablejs#147]
Hello @smnbbrv ,

Can you please upgrade angular-sortablejs to Sortablejs 1.8.1 (Latest) because it has some interesting features and the one currently we are more interested is "swapThreshold" property?

Because currently we have a use case where each individual item is also a sortable so when the user is trying to drop onto it then it is kind of triggering a reorder (sort) which we want to avoid and give some time to trigger drop action instead of sort operation. It looks like "swapThreshold" is a perfect or an apt solution I can think of at this moment.

Reference Link: http://sortablejs.github.io/Sortable/

Thanks,
Bhasker

**Comment by bhaskerchari** [comment]
@smnbbrv ,

I do not have Git access from work place for security reasons so I am not able to send pull request.

Yes you are right but to take full advantage of the latest sortablejs changes all those newly added properties needs to be added to SortablejsOptions ts file that's the reason I logged an item for an upgrade.

I feel it would be better if some one can upgrade to support latest changes :)

Thanks,
Bhasker

**Comment by bhaskerchari** [comment]
Can some one please upgrade if anyone is interested or else I will try to give it a shot from home when I find time?

Thanks,
Bhasker

**Comment by Marlaqk** [comment]
Hi @bhaskerchari 
I added the new properties. Waiting for PR approval.

cheers,
Ralph

**Comment by smnbbrv** [comment]
Hi guys,

please check latest version
