### ISSUE TITLE
Remove on spill / drop out

### ISSUE THREAD

**Issue by mirzinho** [SortableJS/ngx-sortablejs#153]
Hello,

been going trough the documentation and issues but could not find anything that would give a single clue how to achieve this.

Wanted behavior:
When I drag an item and drop it outside of list container it should be removed from list or at least give info that it has been dropped out of the list.

Anyone encountered this problem?

Thank you

**Comment by smnbbrv** [comment]
Hi @mirzinho 

try to search for this behaviour in [sortablejs/sortable](https://github.com/SortableJS/Sortable). 

Actually my first attempt would be to put sortable on the very root parent container (where you drop the item to) to get notifications from there when the item gets dropped. The configuration would be e.g.

- filtering all the children elements away (that you can't sort them)
- ghost and other involved classes should hide the droppable item to avoid content fluctuations, etc

However I have a feeling this approach could have some weird artifacts after. Would be really interesting to see the solution; if you find one please post it!

**Comment by mirzinho** [comment]
HI @smnbbrv ,

I did some research but no luck on any area. So, i wrote my own piece of code, a little bit dirty, quick fix solution if i can call it like that.

Uses jQuery to get element area and compare it to the mouse events that ScrollableJS emits.

I am using two events to determine whether the element is placed in the list or out of the list.

If it helps  someone or can improve on it, you are more than welcome.

```
    public dragableArea: any = {
      top: 0,
      left: 0,
      width: 0,
      height: 0,
    };

    constructor() {
      let self = this;

      this.playlistSortableOptions = {
        filter: '.non-movable',
        sort: true,
        group: {
          name: 'clone-group',
        },
        onStart: function(event: any) {
          let draggableContainer = $('.scrollable-div');
          self.dragableArea = {
            top: draggableContainer.offset().top,
            left: draggableContainer.offset().left,
            width: draggableContainer.width(),
            height: draggableContainer.height(),
          };
        },
        onEnd: function(event: any) {
          let inX = (event.originalEvent.x >= self.dragableArea.left && event.originalEvent.x <= (self.dragableArea.left + self.dragableArea.width));
          let inY = (event.originalEvent.y >= self.dragableArea.top && event.originalEvent.y <= (self.dragableArea.top + self.dragableArea.height));
          if (inX && inY ) {
            self.reorderList(event.newIndex);
          }
          else {
            console.log('REMOVE ON SPILL')
          }

        },
        onRemove: function(event: any) {
        },
        onMove: function(event: any): boolean {
          return true;
        },
        onClone: function(event: any) {
        },
        onAdd: function(event: any) {
          self.itemDroppedToList(event.newIndex);
        },
      };
    }
      
```

**Comment by owen-m1** [comment]
@mirzinho Available in this branch currently: https://github.com/SortableJS/Sortable/tree/next-version/plugins/OnSpill

**Comment by mirzinho** [comment]
Great info, for future.
I ended up refining the code from previous post and  so far works without a glitch, in Any case thank you for the link.

Cheers
