### ISSUE TITLE
Angular Universal Issue

### ISSUE THREAD

**Issue by lehoffma** [SortableJS/ngx-sortablejs#157]
Hey,
I tried using this library in an [Angular Universal](https://angular.io/guide/universal) app, but I always get this runtime error: 

```
ERROR TypeError: OriginalSortable.create is not a function
    at <path\to\source>
```

The stack trace points to [this line](https://github.com/SortableJS/angular-sortablejs/blob/master/src/sortablejs.directive.ts#L40). 

The errors occur only when deployed with angular universal, otherwise everything works fine. I'm using v2.7.0 (and `sortablejs` v1.9.0).

**Comment by smnbbrv** [comment]
Hi,

please check `npm i ngx-sortablejs` (attention, **the project was renamed**)

**Comment by louis-rogeon** [comment]
> Hi,
> 
> please check `npm i ngx-sortablejs` (attention, **the project was renamed**)

Hi,

I encountered the same problem, with Angular 7 (using angular-sortablejs).
The new package ngx-sortablejs is not compatible with Angular < 8. 
What do you recommend in this case ?

**Comment by smnbbrv** [comment]
I don't think I can anyhow fight this issue on angular < 8 because this limitation comes from angular-cli which is building the project. I would highly recommend to migrate from v7 to v8 anyway, because v7 is not LTS version...

**Comment by rorry121** [comment]
angular6 the same problem....
