### ISSUE TITLE
there is a compilation error with angular 8 with Ivy enabled

### ISSUE THREAD

**Issue by sfabriece** [SortableJS/ngx-sortablejs#159]

**Comment by marcelcremer** [comment]
Got the same issue - issue is coming from ivy not bein able to parse non-ng-modules.

See https://github.com/angular/angular/issues/29564 for further information.

Might be a good idea to use 

https://github.com/ng-packagr/ng-packagr

 as it creates umd/es5 / ... bundles. With it's output, every format should be supported and therefore future-proof.

**Comment by smnbbrv** [comment]
Would be good to migrate the repo to angular cli I guess

**Comment by sfabriece** [comment]
support for `ng add` would be awesome, anything we can do to move this along? @smnbbrv

**Comment by smnbbrv** [comment]
Hi guys,

please check `npm i ngx-sortablejs` (attention, **the project was renamed**).

Does it work for you?

**Comment by smnbbrv** [comment]
@sfabriece what would you like to put into `ng add`? The installation is quite simple, the only thing I see is installing `sortablejs` under the hood :) Is there any benefit for that?

**Comment by sfabriece** [comment]
Good point @smnbbrv. It's probably not needed.

**Comment by johnfedoruk** [comment]
The compiler error
```bash
sortable export 'ɵɵdefineInjectable' was not found in '@angular/core
```
 is only found in [v3.0.0](https://github.com/SortableJS/ngx-sortablejs/releases/tag/v3.0.0) using the package [ngx-sortablejs@3.0.0](https://www.npmjs.com/package/ngx-sortablejs) and not in [v2.7.0](https://github.com/SortableJS/ngx-sortablejs/releases/tag/v2.7.0) using the package [angular-sortablejs@2.7.0](https://www.npmjs.com/package/angular-sortablejs).

Here is my environment:

```plaintext
Angular CLI: 6.2.9
Node: 8.9.4
OS: linux x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.8.9
@angular-devkit/build-angular      0.10.7
@angular-devkit/build-ng-packagr   0.10.7
@angular-devkit/build-optimizer    0.10.7
@angular-devkit/build-webpack      0.10.7
@angular-devkit/core               0.8.9
@angular-devkit/schematics         0.8.9
@angular/cli                       6.2.9
@angular/pwa                       0.8.9
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.0.7
@schematics/angular                0.8.9
@schematics/update                 0.8.9
ng-packagr                         4.7.1
rxjs                               6.2.2
typescript                         2.9.2
webpack                            4.19.1
```

**Comment by smnbbrv** [comment]
Probably that’s the version of angular. Do you consider to upgrade to v8? I don’t think I can keep supporting old angular versions...

**Comment by smnbbrv** [comment]
OK, as long there is no Ivy complaints anymore I assume it is fixed. If I'm wrong, please reopen it

**Comment by sfabriece** [comment]
Thanks @smnbbrv  😄
