### ISSUE TITLE
Uncaught Sortable: `el` must be HTMLElement, and not [object Window]

### ISSUE THREAD

**Issue by Kuroiyatsu** [SortableJS/ngx-sortablejs#162]
Setting things up exactly as listed in the readme file, I continue to get this error:

Uncaught Sortable: `el` must be HTMLElement, and not [object Window], and cannot use sortable.

It appears straight-foward, but just does not work for me. Is there something missing in the readme that handles initialization?

![image](https://user-images.githubusercontent.com/15186657/59113186-34cc6700-890a-11e9-907f-7221632bc10b.png)

![image](https://user-images.githubusercontent.com/15186657/59113224-46ae0a00-890a-11e9-89dd-d4367b4e10ea.png)

![image](https://user-images.githubusercontent.com/15186657/59113278-59c0da00-890a-11e9-90f1-72155e41f98b.png)

**Comment by smnbbrv** [comment]
Hi @Kuroiyatsu 

thank you for reporting, I can reproduce the issue. Gimme some minutes, I'll try to release the fix

**Comment by smnbbrv** [comment]
try `npm update`

**Comment by Kuroiyatsu** [comment]
Sweet! Ran the npm upate and that worked. Thanks!
