### ISSUE TITLE
Using ngx-sortablejs with Angular 8

### ISSUE THREAD

**Issue by 3ddesign** [SortableJS/ngx-sortablejs#163]
Ngx-sortablejs with Angular 8.0.1 does not work and does not show any errors.
Connected according to the documentation: https://www.npmjs.com/package/ngx-sortablejs
As I understand, the support of Angular 8 is already implemented?

**Comment by smnbbrv** [comment]
Hi,

Please provide an example.

**Comment by 3ddesign** [comment]
[sortable-test.zip](https://github.com/SortableJS/ngx-sortablejs/files/3305226/sortable-test.zip)

**Comment by 3ddesign** [comment]
Maybe it is somehow not properly connected? I can not figure out the reason (

**Comment by Gedmcq** [comment]
Hi,

have the same problem after upgrade, any updates?

**Comment by 3ddesign** [comment]
Hi,
I did not make updates. Created a project today with the latest versions:
    "ngx-sortablejs": "3.1.1",
    "sortablejs": "1.10.0-rc2"

**Comment by smnbbrv** [comment]
hem. Looks like the problem is here

https://github.com/SortableJS/ngx-sortablejs/blob/417cce73754c245d567a6213b9611ffb4a990f60/projects/ngx-sortablejs/src/lib/sortablejs.directive.ts#L2

Typo in import... I gonna fix it asap.

**Comment by smnbbrv** [comment]
Try 3.1.2

**Comment by smnbbrv** [comment]
Otherwise, please reproduce the issue on stackblitz.

See, with the wrong library installed it works right now:

https://stackblitz.com/edit/angular-8wg78w?file=src/app/app.module.ts

**Comment by 3ddesign** [comment]
This is strange, on stackblitz works fine, but if I download it locally, it does not work. You can reproduce it, I think the result will be the same

**Comment by smnbbrv** [comment]
If I use the sortablejs@1.9.0 then it works pretty well.

The issue seem to come in 1.10.0-rc2.

I don't really know what's changed there and fixing the potentially buggy RC version is also something I'd like to avoid.

So, I'd suggest using 1.9.0 for now

**Comment by 3ddesign** [comment]
> [sortable-test.zip](https://github.com/SortableJS/ngx-sortablejs/files/3305226/sortable-test.zip)

the same as here.
Can you reproduce it locally?

**Comment by smnbbrv** [comment]
I can, and it works locally with 1.9.0

**Comment by smnbbrv** [comment]
@3ddesign I created an issue on the main repo, let's wait for more info

**Comment by 3ddesign** [comment]
Yes, with version 1.9.0 works fine! 
Thanks!

**Comment by Mantisimo** [comment]
Same here, 1.9.0 works for me! Cheers
