### ISSUE TITLE
Deep clone element

### ISSUE THREAD

**Issue by alator21** [SortableJS/ngx-sortablejs#169]
Is there a way to deep clone an element when moving between two lists? Right now when I clone an element, it still references the original. This might be a similar issue https://github.com/SortableJS/Vue.Draggable/issues/21 

Example:
I got two lists. I clone elements from list A to list B.
I double click an element to list B(changing his state).
The same change happens to the original element in the A list.
Here is a stack blitz implementation https://stackblitz.com/edit/angular-myond7.

There should be a way(an option maybe) so I can deep clone the element when I move it.

**Comment by smnbbrv** [comment]
https://github.com/SortableJS/ngx-sortablejs#drag--drop-between-two-lists-clone-mode

Please read carefully: use `sortablejsCloneFunction` to change the default cloning method

**Comment by alator21** [comment]
Thanks, @smnbbrv. For future reference, in my case, I needed to copy an object so in my clone implementation, I returned a deep copy of my object.
