### ISSUE TITLE
Build error in version 3.1.4 Cannot use namespace 'Options' as a type sortablejs-options.d.ts 

### ISSUE THREAD

**Issue by tomastalian** [SortableJS/ngx-sortablejs#181]
After upgrating to new version "ngx-sortablejs": "^3.1.4", getting this error message on build:

ERROR in node_modules/ngx-sortablejs/lib/sortablejs-options.d.ts(6,41): error TS2709: Cannot use namespace 'Options' as a type.

**Comment by smnbbrv** [comment]
Hi @tomastalian 

now it is required to install sortable typings

```
npm i -D @types/sortablejs
```

Looks like it's an unexpected breaking change though...

**Comment by tomastalian** [comment]
Hi @smnbbrv 

Thank for quick and working solution. 

After 
`npm i -D @types/sortablejs`
is working
