### ISSUE TITLE
Looking for maintainer

### ISSUE THREAD

**Issue by smnbbrv** [SortableJS/ngx-sortablejs#197]
Hello everybody,

several years ago I started this project with angular 2 beta versions and guided it through to the current state.

Unfortunately, I cannot give it as much attention as it deserves anymore. I simply don't have projects that use it + wherever it was possible I already switched to using native @angular/cdk drag and drop modules.

That's why it's necessary that some of you who uses the project a lot can take it over. There are many issues waiting for a long time.

If you are interested in this, please write here.

Please think twice before applying and be ready to work a lot.

**Comment by shubhamt619** [comment]
Hi @smnbbrv ,

Thanks a lot for working so Hard for this, If you could just merge #198 , It would be great.
Please do it Asap

**Comment by CodingCloud9527** [comment]
@smnbbrv  I want to make an effort, What do I need to do for this?

**Comment by smnbbrv** [comment]
Hi @CodingCloud9527 

we need to contact the main admin that he adds you as maintainer.

**Comment by smnbbrv** [comment]
Hi @owen-m1 

could you please organize adding the maintainer to the team? The project is stuck with lots of issue requests and I have no time to proceed with developing it. If you think some sort of interview is required, it can of course take place I guess

**Comment by waynevanson** [comment]
@smnbbrv, @CodingCloud9527 has now been added with `maintain` permissions :)

**Comment by smnbbrv** [comment]
Super, thanks!

**Comment by smnbbrv** [comment]
@CodingCloud9527 please share your npm account that we can give you package publish permissions

**Comment by CodingCloud9527** [comment]
@smnbbrv  my npm account is codingcloud9527 , same as my github account

**Comment by smnbbrv** [comment]
@CodingCloud9527 done, you are the maintainer in repo and npm now. Please feel free to start contributing :)

**Comment by CodingCloud9527** [comment]
@smnbbrv  ok, I will deal with these issues in my free time
